### ISSUE TITLE
Issue while making second call.

### ISSUE THREAD

**Issue by rescue1155** [ccabrerar/ViciPhone#1]
Facing an issue 

First time make a call works,  Then unable to make second call due to JS errors.
find the attached image.

![image](https://user-images.githubusercontent.com/15667762/92176148-5131b900-ee57-11ea-8b16-b1417fe56173.png)

**Comment by ccabrerar** [comment]
Interesting. Never thought of it because you aren't supposed to dial directly from Viciphone while on Vicidial. 

If I may ask: Are you using the webphone outside of Vicidial, or why are you manually dialing from within Viciphone instead of using the agent interface?

**Comment by rescue1155** [comment]
Yes, I'm using outside of VICIdial and I have integrated that phone to my website using iFrame.
Where poeple can make free calls to USA / Canada and Brazil.

Yes, that outside of agent interface also, That's hosted some other site and using wss:// connected to my VICIdial server.

**Comment by ccabrerar** [comment]
I'm trying to replicate these errors in my test environment but I don't run into the problem. I'm able to dial once, hangup, then dial again.

Got it published anywhere where I could test it?

**Comment by rescue1155** [comment]
Please you can check demo at:
https://phone.dererumsalute.com/phone/phone.php?phone_login=1002&phone_pass=1002

let say you make a call to 1003 then hangup, then again call etc...
You will see the error in console.


Please Note:
I have comment the code of base64_decode(), Because I am passing login / password directly from URL.

**Comment by rescue1155** [comment]
?

**Comment by carpenox** [comment]
add a favicon.ico file

**Comment by ccabrerar** [comment]
Several improvements have been made to the way sessions are handled inside of Viciphone. Please try the 2.1 branch and if problems persists, please re-open the issue and allow us a new demo to test it.
