### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by bylli79** [ccabrerar/ViciPhone#2]
Hello,
when I call, I don't hear the audio.
The person I call hears my voice.
What can I do?

**Comment by carpenox** [comment]
it sounds like a bandwith issue, your download speed may be slow, check fast.com, is it less than 2mb?

**Comment by carpenox** [comment]
message me on skype and ill try to help you debug it skype: live:carpenox_3

**Comment by ccabrerar** [comment]
Closing issue as it would be related to Asterisk configuration or sipjs configuration. If you can supply console evidence pointing out to a Viciphone error, please re-open.
