### ISSUE TITLE
Viciphone se queda conectando 

### ISSUE THREAD

**Issue by Degel393** [ccabrerar/ViciPhone#5]
Buenos días Christian tengo un problema con Viciphone  lo instale pero cuando ingreso a la web solo se queda en connecting no arroja la llamada de bienvenida

**Comment by ccabrerar** [comment]
Si se queda en "Connecting", es que no está negociando correctamente contra Asterisk/Vicidial. En esta versión es requisito tener el ```rtcp_mux=yes``` en la plantilla SIP para que las llamadas sean aceptadas.

**Comment by Degel393** [comment]
asi lo tengo configurado 

type=friend
host=dynamic
encryption=yes
icesupport=yes
directmedia=no
transport=wss
dtlsenable=yes
dtlsverify=no
dtlscertfile=/etc/certbot/live/XXXXXXXXXX/cert.pem
dtlsprivatekey=/etc/certbot/live/XXXXXXXXXXX/privkey.pem
dtlssetup=actpass
rtcp_mux=yes

**Comment by ccabrerar** [comment]
Aún así, eso no dice que el resto de los puntos esté correctamente configurado. Por ejemplo, el certificado podría no ser válido, Asterisk podría no estar escuchando en el puerto 8089, el archivo http.conf podría no estar bien configurado, o tu firewall podría no estarle permitiendo el paso a tu webphone.

Son muchas las variables que hay que checar *antes* de pensar que el código del webphone es el problema. Posiblemente la consola de JS de tu navegador te de más detalles sobre lo que pueda estar mal.

**Comment by Degel393** [comment]
ok me pondré a revisar mas a fondo muchas gracias
