### ISSUE TITLE
Cómo configurar un TURN server? 

### ISSUE THREAD

**Issue by egorky** [ccabrerar/ViciPhone#6]
He buscado la documentación y no se indica dónde puedo poner mi TURN server en la configuración, me pueden ayudar?

**Comment by ccabrerar** [comment]
Podrías modificar el ```vici_phone.js``` para conseguirlo, pero se supone que el uso de Viciphone es a través de Vicidial, y que para ello la llamada se establece cuando Vicidial te manda la llamada, no al revés.

Por tal motivo, el servidor TURN debería de especificarse dentro de la configuración del servidor de Asterisk, no del teléfono. Más especificamente en el ```/etc/asterisk/rtp.conf```

**Comment by egorky** [comment]
Gracias @ccabrerar  por tu pronta respuesta. 
Antes ya había cambiado el STUN server a uno propio en el archivo rtp.conf y aún así el webphone llama a google.
![image](https://user-images.githubusercontent.com/54412925/138496324-ce77dedf-c456-4e0a-97b4-6227ac717da3.png)
presumí que la configuración debía estar grabada en el mismo teléfono.

**Comment by ccabrerar** [comment]
Cada elemento de la llamada usará su propio servidor STUN para obtener la IP pública desde la cual está comunicándose. Dado que en Asterisk puedes configurar el NAT, aunque un cliente especifique incorrectamente su IP pública (por no tener el STUN correctamente configurado), Asterisk debería de ser capaz de darse cuenta de esto y omitir el uso de la IP privada del cliente y reemplazar la por la IP pública desde la cual está recibiendo el tráfico. 

Al configurar el STUN dentro de ```rtp.conf```, Asterisk usará ese servidor para obtener la IP pública (de Asterisk) y comunicársela al cliente. Cuando el cliente responda, Asterisk podrá ver de donde viene el tráfico y auto-ajustarse conforme a los parámetros de NAT que tenga puestos.

En otras palabras, el uso de STUN es más imperativo para quien comienza la llamada, porque desde el primer momento tiene que avisarle al otro extremo sobre cual es la IP pública que este tiene.

Si aún con esto necesitas cambiar el STUN dentro del cliente (Viciphone), necesitas modificar a mano el ```vici_phone.js```, ya que actualmente no hay una manera prevista de cambiarlo desde el template. El elemento a modificar es la variable ```ua_config``` (lo encuentras en la [linea 81](https://github.com/ccabrerar/ViciPhone/blob/27872bed13f31528691d69653fe96c70c9f53ae4/js/vici_phone.js#L81)), y tienes que agregarle este elemento:
```
        sessionDescriptionHandlerFactoryOptions: {
                rtcConfiguration: {
                        iceServers: [{urls: 'stun:stun.l.zoom.com:19302'}]
                },
        },
```
Obviamente, reemplazando el STUN que puse allí por el que sea de tu preferencia.

Con el cambio, el objeto completo debería quedar como algo así:
```
var ua_config = {
        userAgentString: 'VICIphone 2.1',
        displayName: cid_name,
        uri: sip_uri,
        hackIpInContact: true,
        hackViaTcp: true,
        hackWssInTransport: true,
        authorizationUser: auth_user,
        password: password,
        log: {
                builtinEnabled: true,
                level: "debug",
        },
        transportOptions: {
                traceSip: true,
                wsServers: ws_server,
        },
        autostart: true,
        registerOptions: {
//              expires: 900
        },
        sessionDescriptionHandlerFactoryOptions: {
                rtcConfiguration: {
                        iceServers: [{urls: 'stun:stun.l.zoom.com:19302'}]
                },
        },
}
```

El apartado llamado ```stunServers``` actualmente está depreciado. En una nueva versión del código que libere, quitaré ese apartado y dejaré el que acabo de darte por si alguien desea hacer el cambio manualmente en el futuro.

**Comment by egorky** [comment]
muchísimas gracias por tu apoyo, @ccabrerar . Esto me ayuda mucho.
