### ISSUE TITLE
Es posible cambiar las dimensiones del webphone? Can I resize the webphone?

### ISSUE THREAD

**Issue by egorky** [ccabrerar/ViciPhone#7]
En las el archivos options.php de ViciDial dice que se puede colocar el webphone en la parte superior de la pantalla y hacerlo más delgado. Es posible esto con Viciphone? en qué archivos se cambia la organización de botones y tamaños?

**Comment by ccabrerar** [comment]
Claro. Toda la apariencia es por CSS. En el subdirectorio CSS está el archivo que se suele utilizar (default.css), pero puedes usar el formato thin.css, o puedes crear e invocar los tuyos propios.  Esto se hace desde Vicidial, cambiando el URL del layout.

**Comment by egorky** [comment]
entendido, muchas gracias!
